---
experiment_name: 'ncf_binarize'

binarize: true

# train_csv: musicRatings.csv
# data_config:
  

train_config:
  max_epochs: 20

model_type: NCF
model_config:
  factor_num: 8
  num_layers: 2
  dropout: 0.1
  model: MLP